"""add_indexes_to_foreign_keys

Revision ID: b0eb64c79e16
Revises: d343b386aeac
Create Date: 2025-10-24 13:43:03.529649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0eb64c79e16'
down_revision = 'd343b386aeac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###