"""Add external_user_id to submissions and redirect URLs to surveys

Revision ID: d343b386aeac
Revises: 05df0306ab3d
Create Date: 2025-10-24 13:58:16.759224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd343b386aeac'
down_revision = '05df0306ab3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_response_id'), table_name='media')
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_question_type'), table_name='responses')
    op.drop_index(op.f('ix_responses_responded_at'), table_name='responses')
    op.drop_index(op.f('ix_responses_submission_id'), table_name='responses')
    op.add_column('submissions', sa.Column('external_user_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_submissions_email'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_is_approved'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_is_completed'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_region'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_survey_approved'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_survey_completed'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_survey_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_survey_submitted'), table_name='submissions')
    op.create_index(op.f('ix_submissions_external_user_id'), 'submissions', ['external_user_id'], unique=False)
    op.add_column('surveys', sa.Column('complete_redirect_url', sa.String(), nullable=True))
    op.add_column('surveys', sa.Column('screenout_redirect_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_surveys_active_created'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_client'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_created_at'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_is_active'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_name'), table_name='surveys')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_surveys_name'), 'surveys', ['name'], unique=False)
    op.create_index(op.f('ix_surveys_is_active'), 'surveys', ['is_active'], unique=False)
    op.create_index(op.f('ix_surveys_created_at'), 'surveys', ['created_at'], unique=False)
    op.create_index(op.f('ix_surveys_client'), 'surveys', ['client'], unique=False)
    op.create_index(op.f('ix_surveys_active_created'), 'surveys', ['is_active', 'created_at'], unique=False)
    op.drop_column('surveys', 'screenout_redirect_url')
    op.drop_column('surveys', 'complete_redirect_url')
    op.drop_index(op.f('ix_submissions_external_user_id'), table_name='submissions')
    op.create_index(op.f('ix_submissions_survey_submitted'), 'submissions', ['survey_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_submissions_survey_id'), 'submissions', ['survey_id'], unique=False)
    op.create_index(op.f('ix_submissions_survey_completed'), 'submissions', ['survey_id', 'is_completed'], unique=False)
    op.create_index(op.f('ix_submissions_survey_approved'), 'submissions', ['survey_id', 'is_approved'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_at'), 'submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_submissions_region'), 'submissions', ['region'], unique=False)
    op.create_index(op.f('ix_submissions_is_completed'), 'submissions', ['is_completed'], unique=False)
    op.create_index(op.f('ix_submissions_is_approved'), 'submissions', ['is_approved'], unique=False)
    op.create_index(op.f('ix_submissions_email'), 'submissions', ['email'], unique=False)
    op.drop_column('submissions', 'external_user_id')
    op.create_index(op.f('ix_responses_submission_id'), 'responses', ['submission_id'], unique=False)
    op.create_index(op.f('ix_responses_responded_at'), 'responses', ['responded_at'], unique=False)
    op.create_index(op.f('ix_responses_question_type'), 'responses', ['question_type'], unique=False)
    op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_media_response_id'), 'media', ['response_id'], unique=False)
    # ### end Alembic commands ###