"""add_composite_indexes_for_query_optimization

Revision ID: e8213a8b0e49
Revises: b0eb64c79e16
Create Date: 2025-10-24 14:10:22.659277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8213a8b0e49'
down_revision = 'b0eb64c79e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add composite indexes to Submission table for query optimization
    op.create_index('ix_submission_survey_approved', 'submissions', ['survey_id', 'is_approved'])
    op.create_index('ix_submission_survey_completed', 'submissions', ['survey_id', 'is_completed'])
    op.create_index('ix_submission_survey_approved_completed', 'submissions', ['survey_id', 'is_approved', 'is_completed'])
    op.create_index('ix_submission_demographics', 'submissions', ['survey_id', 'region', 'gender'])

    # Add composite index to Response table
    op.create_index('ix_response_submission_type', 'responses', ['submission_id', 'question_type'])

    # Add composite index to ReportingLabel table
    op.create_index('ix_reporting_label_survey_name', 'reporting_labels', ['survey_id', 'label_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove composite indexes
    op.drop_index('ix_reporting_label_survey_name', table_name='reporting_labels')
    op.drop_index('ix_response_submission_type', table_name='responses')
    op.drop_index('ix_submission_demographics', table_name='submissions')
    op.drop_index('ix_submission_survey_approved_completed', table_name='submissions')
    op.drop_index('ix_submission_survey_completed', table_name='submissions')
    op.drop_index('ix_submission_survey_approved', table_name='submissions')
    # ### end Alembic commands ###